### ISSUE TITLE
Color black

### ISSUE THREAD

**Issue by sbyujx** [orbotix/sphero.js#24]
when use color("black"), the terminal show "invalid color provided black".
it seems that the sphero.js can't accpet this color.
if i change the code to color(0x0), the sphero turns to white color.
so how to ture off the RGB led of sphero?

**Comment by dimorphic** [comment]
True, seems `black` is not recognized.
I got it working by using `0x0` or `0x000000` instead of `black`, and not as string.

Eg: `orb.color(0x0)` and not `orb.color('0x0')`.

**Comment by brianfeister** [comment]
Sorry but @dimorphic but your solution is not working for me when I test it your solutions, they all log `invalid color provided`.  I'm unclear on whether or not this is possible.
