### ISSUE TITLE
Does this package support ollie?

### ISSUE THREAD

**Issue by omeryagmurlu** [orbotix/sphero.js#27]
Does this package support ollie? Otherwise, are you working on making ollie a similar package?

**Comment by mcgrews3** [comment]
+1

**Comment by omeryagmurlu** [comment]
I've written a similar (it is not capable of doing everything this SDK) SDK for Ollie [here](https://github.com/omeryagmurlu/olliejs/). Someone may want to take a look at it. Right now I'm writing a controller for Ollie with it.

**Comment by deadprogram** [comment]
Hi, everyone.

The new `master` branch now includes full Ollie & BB-8 support. Please check it out!

**Comment by mcgrews3** [comment]
Awesome!  Will check it out and thanks for the update!!!

**Comment by deadprogram** [comment]
The conversation on #26 also includes a lot of Ollie, so I'd like to close this issue in favor of that one, if there are no objections.
