### ISSUE TITLE
Simplify installation by adding `noble` and `serialport` to project dependencies

### ISSUE THREAD

**Issue by zaccolley** [orbotix/sphero.js#43]
Related to https://github.com/orbotix/sphero.js/pull/42.

Could the project require both dependencies and use config options to determine which device is being used?

This would probably simplify the installation process and make the examples clearer?

e.g
```JavaScript
device = sphero('########', { device: 'ollie' });
```

```JavaScript
device = sphero('########', { device: 'bb8' });
```

```JavaScript
device = sphero('########'); // falls back to original setup
```

**Comment by deadprogram** [comment]
Thanks for the comment @zaccolley we cannot do this, due to not all machines (especially older Windows) having the BLE stack needed to install Noble. We want to allow those users to continue to use Sphero.js in their use case. Hence the current more "dynamic" dependency.

**Comment by zaccolley** [comment]
OK gotcha
