### ISSUE TITLE
orb.color not working

### ISSUE THREAD

**Issue by kdinluks** [orbotix/sphero.js#59]
Since last commit dff80df "Minor formatting changes" the function color() is not working.
Probably due to the changes on function hexToRgb().

**Comment by deadprogram** [comment]
I should never make such commits, and this is more proof. I will revert that commit.

**Comment by deadprogram** [comment]
Done: https://github.com/orbotix/sphero.js/commit/c5a50ed69c29eb03ae1ec9a622d7f4533c7d1edc

Thank you for pointing this out.

**Comment by deadprogram** [comment]
Hi, @kdinluks this was resolved. Please reopen if you think it requires further attention. Thanks again.
