### ISSUE TITLE
Cannot open /dev/rfcomm0 - Ubuntu

### ISSUE THREAD

**Issue by MartinT86** [orbotix/sphero.js#64]
Hi,

I'm an Ubuntu newbie and I'm struggling to use the sphero package.
Using your main example I am just getting the following error;
Cannot open /dev/rfcomm0

I have connected the sphero using bluetooth manager and it says the device is connected.
I have also added the following to a new file called - /etc/udev/rules.d/55-rfcomm.rules;
KERNEL=="rfcomm[0-9]*", NAME="%k", GROUP="dialout"

Any help would be great.

Thanks

**Comment by deadprogram** [comment]
You might not be a member of the `dialout` group, run `whoami` and  `groups`. One way to test permission problems, is to run your code under sudo.

Hope that helps!

**Comment by MartinT86** [comment]
thanks for the fast reply!

yes, looks like it was a permission issue. I'm now running it as "sudo node app.js" and it runs.

thanks again
