### ISSUE TITLE
Raw Motors

### ISSUE THREAD

**Issue by DarrenGuinness** [orbotix/sphero.js#68]
Is it possible to send raw motor commands using the sphero.js API?

**Comment by deadprogram** [comment]
Hi @DarrenGuinness yes, checkout https://github.com/orbotix/sphero.js/blob/800142d15d0a3276f3df529e8306dd295e579a16/lib/devices/sphero.js#L466-L507

```
var opts = {
  lmode: 0x01,
  lpower: 180,
  rmode: 0x02,
  rpower: 180
}

orb.setRawMotors(opts, function(err, data) {
  console.log(err || "data: " + data);
}
```

**Comment by DarrenGuinness** [comment]
Thank you very much. This should work for me.
