### ISSUE TITLE
Configure SpheroJS for Windows 10

### ISSUE THREAD

**Issue by Xstoudi** [orbotix/sphero.js#72]
Hey there !
I tried to use SpheroJS to command my BB-8 Sphero.
I successfully installed sphero and noble packages but when I start this script:
```javascript
var sphero = require("sphero");
var orb = sphero("XX:XX:XX:XX:XX:XX");

orb.connect(function() {
    console.log("BB-8 connected");
    orb.color("blue");
    orb.roll(360, 0)
});
```

it tell me this : 
```
It looks like you want to connect to a Sphero BB-8 or Sphero Ollie,
but did not install the 'noble' module.

To install it run this command:
npm install noble

For more information go to https://github.com/sandeepmistry/noble
X:\Programmation\NodeJS\bb8\node_modules\sphero\lib\adaptors\ble.js:33
    throw new Error("Missing noble dependency");
    ^

Error: Missing noble dependency
```

By the way, noble is installed !

So please, can you edit your README to give me the instructions that allow me to make things work.

Thanks !
Xavier

**Comment by JoshuaJB** [comment]
Noble requires a lot of auxiliary configuration to work on Windows. See [this](https://www.youtube.com/watch?v=mL9B8wuEdms) setup guide.
